#!/bin/bash

echo "🗄️  Fix-It Hub Database Explorer"
echo "================================"
echo ""
echo "Quick Database Commands:"
echo ""
echo "📋 View all users:"
echo "   db.users.find().pretty()"
echo ""
echo "📋 View all listings:"
echo "   db.listings.find().pretty()"
echo ""
echo "🔢 Count documents:"
echo "   db.users.countDocuments()"
echo "   db.listings.countDocuments()"
echo ""
echo "🔍 Find specific user by email:"
echo "   db.users.findOne({ email: 'user@example.com' })"
echo ""
echo "🗑️  Delete all data:"
echo "   db.users.deleteMany({})"
echo "   db.listings.deleteMany({})"
echo ""
echo "================================"
echo "Starting MongoDB Shell..."
echo ""

mongosh mongodb://localhost:27017/fixithub
